version: "3"  # docker-compose版本
services:
  docker-python-demo:  # docker-compose编排名称，一般同微服务名称，注意不要与其他服务重名
    image: "python:3.6"  # docker镜像名及版本
    hostname: docker-python-demo  # docker容器主机名
    container_name: docker-python-demo  # docker容器名
    volumes:  # 挂载目录
      - ./:/usr/src/py  # photo相关
    ports:  # 端口映射
      - "8080:8080"
    working_dir: /usr/src/py/
    environment:  # 配置环境变量
      - TZ=Asia/Shanghai  # 设置时区
    command: bash /usr/src/py/run.sh  # 设置启动命令
    network_mode: bridge  # 网络模式：host、bridge、none等，一般bridge
    restart: unless-stopped  # 自动启动：unless-stopped、always等，unless-stopped为非正常停止则自动启动